# JWT - reuse defaults from main properties
app.jwt.secret=ReplaceWithARealSecretKeyChangeMe123
app.jwt.expiration-ms=86400000

# Default admin
app.admin.username=admin
app.admin.password=admin


spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:24790/railway?useSSL=true&requireSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zxQGGPmoEjcAisJYjtTUMGalRzwgEbIq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
